openapi: 3.0.0
info:
  title: luna.v1
  version: '1.0'
  contact:
    name: Joshua Richardson-Noyes
    url: lunasphere.co.uk/contact
    email: joshua.richardson-noyes@lunasphere.co.uk
  license:
    name: UNLICENSED
  description: Authentication API used by the entire Lunasphere suite to create/login/delete accounts.
servers:
  - url: 'http://lunasphere.co.uk/api'
    description: Production
  - url: 'http://localhost/api'
    description: Development
paths:
  /auth/login:
    post:
      summary: Login to existing Account
      operationId: post-auth-login
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserOPResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserOPResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserOPResponse'
      description: Attempt login with the credentials submitted in the body.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Luna_Login'
      tags:
        - Authentication
  /auth/register:
    parameters: []
    post:
      summary: ''
      operationId: post-auth-register
      responses:
        '204':
          description: Registration Successful
          headers: {}
        '400':
          description: Bad Request - Invalid / incorrect information supplied.
      description: Create an account with the specified details.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Luna_Login'
        description: ''
      tags:
        - Authentication
  /auth/delete:
    parameters: []
    delete:
      summary: Delete User Account
      operationId: delete-auth-delete
      responses:
        '204':
          description: Deletion Successful
          headers: {}
        '500':
          description: Deletion Failed
      description: Deletes the currently authenticated user account.
      parameters: []
      tags:
        - Authentication
      security:
        - JWT - Authentication Token: []
  /auth/update:
    parameters: []
    put:
      summary: Update Account Information
      operationId: put-auth-update
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Luna_Login'
        '401':
          description: Unauthorized
      description: Used to update the currently authenticated account with submitted information.
      security:
        - JWT - Authentication Token: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Luna_Login'
      tags:
        - Authentication
  /auth/info:
    get:
      summary: Current User Information
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Luna_Login'
      operationId: get-auth-info
      description: Get information about the currently authenticated user.
      parameters:
        - schema:
            type: string
          in: header
          name: Authorization
          description: JSON Web Token
      tags:
        - User Info
components:
  schemas:
    UserOPResponse:
      title: UserOPResponse
      type: object
      properties:
        success:
          type: boolean
        msg:
          type: string
        token:
          type: string
      required:
        - success
      x-tags:
        - Authentication
      description: The response object sent by most Luna Auth Requests
    Luna_Login:
      title: Luna Login
      type: object
      x-tags:
        - Authentication
      description: Simple User Account Details for a Lunasphere Account
      properties:
        userId:
          type: integer
        username:
          type: string
        password:
          type: string
        email:
          type: string
        phone:
          type: string
        salt:
          type: string
      required:
        - username
        - password
  securitySchemes:
    JWT - Authentication Token:
      type: http
      scheme: bearer
tags:
  - name: Authentication
    description: Operations and models used for authentication and authorization of a Lunasphere account.
  - name: User Info
    description: Operations and Models used for viewing of public user information.
